###
GET https://ffapi.onrender.com/products

###
DELETE https://ffapi.onrender.com/products/1

###
POST https://ffapi.onrender.com/products
content-type: application/json

{
	"name": "First",
	"price": "121",
	"color": "brown",
	"category": "knitwear",
	"style": "cardigan",
	"size": "xs",
	"material": "wool",
	"gender": "female",
	"ageGroup": "adult",
	"season": "winter",
	"isNew": true,
	"isOuterwear": true,
	"images": [
	"https://assets.burberry.com/is/image/Burberryltd/EC955983-5422-40AF-AE13-A5FEDBACE6D4?$BBY_V2_ML_1x1$&wid=887&hei=887",
	"https://assets.burberry.com/is/image/Burberryltd/7F53A08D-9474-42A0-A5AB-1DD2EA0BDDCD?$BBY_V2_SL_1x1$&wid=887&hei=887"
	],
	"description": "diam vulputate ut pharetra sit amet aliquam id diam maecenas ultricies mi eget mauris pharetra et ultrices neque ornare aenean euismod elementum nisi quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo nec ultrices dui sapien eget mi proin sed libero enim sed faucibus"
}

###
POST https://ffapi.onrender.com/users
content-type: application/json

{
	"firstName": "a",
	"lastName": "e",
	"phone": "1",
	"email": "account@email.com",
	"address": "1",
	"password": "a",
	"cart": [],
	"favourites": [
		12
	],
	"orders": [
		[
			1,
			2
		],
		[
			2,
			2
		],
		[
			3,
			5
		],
		[
			4,
			1
		]
	],
	"id": 4
}